### ISSUE TITLE
Case sensitive includes

### ISSUE THREAD

**Issue by japanoise** [erkyrath/inform6#3]
Some systems (I.E. Linux) can use case-sensitive file systems. This means that in the same directory, files that have the same name but with different cases can exist; e.g. `Parser.h` and `parser.h`.

What this means, is that when an inform source file assumes case-insensitive filesystems and `Include` s with a different casing than what the file is called on the (case-sensitive) system, the build fails. For example (using a fresh clone of inform6lib and the shortest "ruins.inf" example from DM4 §4):

```
~/devel/inform/ruins
❯ inform +/home/chameleon/builds/inform6lib -G ruins.inf
Inform 6.34 (28th June 2018)
line 4: Fatal error: Couldn't open source file "/home/chameleon/builds/inform6lib/Parser.h"
```

Considering the prevalance of `Include "Parser";` and the fact that probably most IF developers will assume case-insensitive filesystems on Windows or OSX, it'd be great if Inform on Linux could compile case-insensitively.

A workaround is renaming or creating symbolic links.

**Comment by erkyrath** [comment]
Yes, this problem has been around since the beginning of Inform. The historical solution has been to distribute the I6 library files with the names "Parser.h", "Grammar.h", "VerbLib.h". But you're right that the library repo (https://github.com/DavidGriffith/inform6lib) doesn't currently do this.

I'm refiling this at http://inform7.com/mantis/ , which is where we track Inform issues (both 6 and 7).

**Comment by erkyrath** [comment]
Filed: http://inform7.com/mantis/view.php?id=2064
